### ISSUE TITLE
Main Folder

### ISSUE THREAD

**Issue by Taimurkhan1999** [jeangatto/ASP.NET-Core-Clean-Architecture-CQRS-Event-Sourcing#14]
Hey, i am learning .Net. How can i resolve this issue
![image](https://github.com/jeangatto/ASP.NET-Core-Clean-Architecture-CQRS-Event-Sourcing/assets/135840023/a19d4bbe-34ba-4def-ab78-4908a3c6c988)

**Comment by jeangatto** [comment]
Hi, I've recently uploaded some patches, try the build and then run the docker-compose command>
1 > dotnet clean Shop.sln --nologo /tl && dotnet build Shop.sln --nologo /tl
2 > docker-compose up --build --abort-on-container-exit --remove-orphans
